### ISSUE TITLE
The link in the github description is dead

### ISSUE THREAD

**Issue by vzemlys** [JeffreyRacine/R-Package-np#12]
The github page description has the following link: http://www.economics.mcmaster.ca/faculty/racinej. It leads to page with the message that this page does not exist.

**Comment by JeffreyRacine** [comment]
Thanks for this... our department migrated to a new server...

**Comment by vzemlys** [comment]
The link works now. Closing the issue. And thanks for the package and the amazing book.

**Comment by JeffreyRacine** [comment]
Thank you for the kind words and for pointing this out...

Jeff
