### ISSUE TITLE
Error in .C()

### ISSUE THREAD

**Issue by wtf13** [JeffreyRacine/R-Package-np#14]
Hi, 
I have been encountering the following error persistently on my computer when trying to run the npudensbw function from the np library: 
Error in .C("np_density_bw", as.double(duno), as.double(dord), as.double(dcon), : "np_density_bw" not available for .C() for package "np". 

Could you kindly advise on the problem please? My np package installation has already been updated to the latest and I am running the code on R version 3.4.1.. 
Would I need any additional installations in order for the code to run smoothly? 
Thanks in advance for your help!

**Comment by JeffreyRacine** [comment]
Greetings,
 
I will need more information per the FAQ – kindly send code to replicate…

**Comment by wtf13** [comment]
Hi Jeffrey, 
Thanks for your quick response!
Here is the error message when I tried to use the function for the mtcars example dataset. 

> library(np)
Nonparametric Kernel Methods for Mixed Datatypes (version 0.60-3)
[vignette("np_faq",package="np") provides answers to frequently asked questions]
[vignette("np",package="np") an overview]
[vignette("entropy_np",package="np") an overview of entropy-based methods]
> data(mtcars)
> hold<-npudensbw(~wt,data=mtcars)
Error in .C("np_density_bw", as.double(duno), as.double(dord), as.double(dcon),  :
  "np_density_bw" not available for .C() for package "np"
Timing stopped at: 0 0 0

Appreciate your support and have a great weekend!

**Comment by JeffreyRacine** [comment]
Can’t replicate on four different platforms (UNIX, Linux, macOS, windows)… try reinstalling R and the np package perhaps?
 
> library(np)
Nonparametric Kernel Methods for Mixed Datatypes (version 0.60-3)
[vignette("np_faq",package="np") provides answers to frequently asked questions]
[vignette("np",package="np") an overview]
[vignette("entropy_np",package="np") an overview of entropy-based methods]
> data(mtcars)
> hold<-npudensbw(~wt,data=mtcars)
> summary(hold)
 
Data (32 observations, 1 variable(s)):
 
Bandwidth Selection Method: Maximum Likelihood Cross-Validation
Formula: ~wt
Bandwidth Type: Fixed
Objective Function Value: -41.60913 (achieved on multistart 1)
 
Var. Name: wt Bandwidth: 0.245701 Scale Factor: 0.6443658
 
Continuous Kernel Type: Second-Order Gaussian
No. Continuous Vars.: 1
Estimation Time: 0.002 seconds
 
>

**Comment by wtf13** [comment]
Already tried to do so but the same result occurs even after reinstallation~ was wondering if the package has dependencies on other software or the internet? I am trying to run it on a computer that is internet-disabled, not sure if this is the cause of the problem. Thank you so much for helping with this!

**Comment by JeffreyRacine** [comment]
Nope… are you using binaries or building from source?

**Comment by wtf13** [comment]
I believe it's the binary distribution of R..

**Comment by JeffreyRacine** [comment]
Something messed up on your system… sounds like a compiler issue… try building from source and see if that resolves…

**Comment by wtf13** [comment]
ok, thanks so much for your advice professor! I would need to have a C compiler installed in my computer to do this then?

**Comment by JeffreyRacine** [comment]
I presume you are using windows…
 
https://cran.r-project.org/bin/windows/Rtools/

**Comment by wtf13** [comment]
looks like I will have to use another computer, cant do the installation on my machine >< but thanks much!!
