### ISSUE TITLE
xlim not working for npplot.bandwidth

### ISSUE THREAD

**Issue by smonto2** [JeffreyRacine/R-Package-np#15]
Greetings,

I was trying to replicate some plots when I realized that `xlim` does not work when I run `plot` on a bandwidth object after a call to `npudistbw`. Just to check, I went through the source code for `npplot.bandwidth` and found calls to `ylim` and `zlim` throughout the code, but not for `xlim`.

Santiago

**Comment by JeffreyRacine** [comment]
Greetings,

Presume you are using the very latest code… will dig into it when time permits, apologies for the oversight.

Jeff

**Comment by JeffreyRacine** [comment]
The latest version should address this issue (many enhancements to plotting with regards to passing additional arguments such as col, xlim, xlab etc.)
