### ISSUE TITLE
How do run np::npregbw() in parallel

### ISSUE THREAD

**Issue by DeFilippis** [JeffreyRacine/R-Package-np#21]
In the readme files for the npregbw function it says the following: "A version of this package using the Rmpi wrapper is under development that allows one to deploy this software in a clustered computing environment to facilitate computation involving large datasets."

I'm wondering where I can find the version of this package that allows one to deploy the software using a compute grid, and if there is a vignette on how to implement this procedure with multiple cores.  

Thanks!

**Comment by JeffreyRacine** [comment]
Greetings,
 
Kindly see my github page and the install instructions, and there are some install instructions under the research tab of my homepage.
 
Best,
 
Jeff
