### ISSUE TITLE
npindexbw with multiplicative but known heteroskedasticity

### ISSUE THREAD

**Issue by kenanh** [JeffreyRacine/R-Package-np#22]
In Klein and Spady (1993) Econometrica article authors state that their single index model can accomodate multiplicative heteroskedasticity of a known type. Is there a way to conduct KleinSpady wit np package with a specified multiplicative heteroskedasticity, and how?

**Comment by JeffreyRacine** [comment]
Greetings,

Not a feature (though the code calls npksum() so perhaps you might modify the R code from the tarball for your purposes).

Jeff
