### ISSUE TITLE
Broken link in the description

### ISSUE THREAD

**Issue by egarpor** [JeffreyRacine/R-Package-np#24]
Just a minor comment about the link in the description of <https://github.com/JeffreyRacine/R-Package-np>. It reads

<http://www.economics.mcmaster.ca/faculty/racinej> (broken)

but it seems it should be

<https://socialsciences.mcmaster.ca/people/racinej>

?

Thanks for the package, is amazing!

**Comment by JeffreyRacine** [comment]
Thanks for the feedback! Fixed.
