### ISSUE TITLE
multicollinearity 

### ISSUE THREAD

**Issue by waynelapierre** [JeffreyRacine/R-Package-np#42]
Does npreg(y ~ x1 + x2) make sense when x1 and x2 are strongly correlated?

**Comment by JeffreyRacine** [comment]
Hi,

Short answer, yes. 

Disentangling the effects is an interesting issue, and npsigtest() proposes a significance test that can be applied to x1 and x2... we ran extensive simulations pushing the correlation to 0.95 and the test was able to distinguish a relevant (say, x1) from an irrelevant predictor (say x2) with power increasing as the sample size grew.

Hope this helps!
