### ISSUE TITLE
Running with seeds that are too large causes R session freeze

### ISSUE THREAD

**Issue by mb706** [JeffreyRacine/R-Package-np#47]
The following causes the R session to freeze:
```r
np::npseed(1114043386)
for (i in 1:10) np::npudensbw(iris[c(1, 51, 101), ])
```
This finishes within a few seconds when using a smaller seed, but this particular seed causes the session to hang.

I believe what is happening is that the `ran3()`-code does not anticipate negative values [here](https://github.com/JeffreyRacine/R-Package-np/blob/97278bba3ef1e3ee5f9a310127d52f4ebfd2ee69/src/nr.c#L532). Note that the C `%`-operator returns negative values when its left-hand operand is negative. If the initial seed is large enough, the `ran3()` return values are no longer between 0 and 1 after a few invocations. The result is an essentially endless loop [here](https://github.com/JeffreyRacine/R-Package-np/blob/97278bba3ef1e3ee5f9a310127d52f4ebfd2ee69/src/nr.c#L588).

Not every large value leads to an R session freeze. I only stumbled upon this because my script runs many restarts with new (random) seeds every time.

The smallest seed that I could find that froze the session is `540714429`. If you want to "mine" for seeds that break the session, you can do
```r
repeat {
  s <- as.integer( (2^31-1) * runif(1))
  cat(sprintf("Trying %s ...\n", s))
  np::npseed(s)
  for (i in 1:10) np::npudensbw(iris[c(1, 51, 101), ])
  # I also tried loops with 200 iterations, but it turns out that pretty much
  # every "bad" seed that I found killed the session after 5 to 7 iterations. 
  cat("seems safe.\n")}
}
```
Once the output gets stuck at `Multistart n of 5 |`, the session is dead.

**Comment by mb706** [comment]
The `ran3()` function seems to be from Numerical Recipes in C, Chapter 7.1. Note that there, the initialization of `mj` is
```c
mj=labs(MSEED-labs(*idum));
```
which avoids negative values by using `labs`.

**Comment by JeffreyRacine** [comment]
Greetings, 

Apologies for the lengthy delay. Thanks for your diligent sleuthing, I will be sure to incorporate this in the next update.

Jeff
